#!/bin/bash

HOSTLIST=slaves

for entry in `cat "$HOSTLIST"|sed  "s/#.*$//;/^$/d"`; do
 parsedentry=$(echo $entry | tr ";" " ")
 slave=${parsedentry[0]}
 host=${parsedentry[1]}
 echo $slave
 echo $host
 ssh $VARYS_SSH_OPTS $slave $"${@// /\\ $host}" \
   2>&1 | sed "s/^/$slave: /" &
 if [ "$VARYS_SLAVE_SLEEP" != "" ]; then
   sleep $VARYS_SLAVE_SLEEP
 fi
done
